# Generated by Django 3.1.3 on 2020-12-02 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mathematics', 'Математика'), ('history', 'История'), ('geography', 'Геогрфия'), ('physics', 'Физика')], max_length=11)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrator.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('student', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('test', models.ManyToManyField(related_name='tests', to='quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('school_class', models.IntegerField(choices=[(1, 'А'), (2, 'Б'), (3, 'В'), (4, 'Г'), (5, 'Д')])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrator.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
