# Generated by Django 3.1.3 on 2020-12-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrator', '0003_auto_20201206_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTest',
        ),
    ]
