# Generated by Django 3.1.3 on 2020-12-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrator', '0004_delete_studenttest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='school',
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('class_letter', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е')], max_length=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registrator.school')),
            ],
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='school_class',
            field=models.ManyToManyField(default=None, to='registrator.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registrator.schoolclass'),
        ),
    ]
