# Generated by Django 3.1.3 on 2020-12-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201206_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Математика', 'mathematics'), ('История', 'История'), ('География', 'Геогрфия'), ('Физика', 'Физика')], max_length=11),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(choices=[('Математика', 'mathematics'), ('История', 'История'), ('География', 'Геогрфия'), ('Физика', 'Физика')], max_length=11),
        ),
    ]
