# Generated by Django 3.1.3 on 2020-12-08 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_auto_20201206_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('student', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('test', models.ManyToManyField(related_name='tests', to='quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(to='quiz.Answer')),
                ('student_test', models.ManyToManyField(to='quiz.StudentTest')),
            ],
        ),
    ]
