# Generated by Django 3.1.3 on 2020-12-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20201211_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttestanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='studenttestanswer',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.answer'),
        ),
        migrations.RemoveField(
            model_name='studenttestanswer',
            name='student_test',
        ),
        migrations.AddField(
            model_name='studenttestanswer',
            name='student_test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.studenttest'),
        ),
    ]
