# Generated by Django 3.1.3 on 2020-12-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20201214_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
